name: Run Unit Tests

#Trigger the workflow on any push to the main branch or pull requests
on:
  push:
    branches:
      - main
      - dev
      - feature/*
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
#Step 1: check out the code from the repo 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
#Step 2: Set up python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
#Step 3: Install Dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#Run Tests
    - name: Install Test Tools
      run: |
        pip install pytest

    - name: Run Unit Tests
      run: |
        pytest -v
 
